config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show]

  resources :users, except: [:destroy] do
    resources :wishlists, except: [:destroy] do
      resources :wishilist_items, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :users
    resources :games
    resources :wishlists
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "games#index"
end

app/models/game.rb
class Game < ApplicationRecord
  include SoftDeletable

  has_many :wishilist_items, dependent: :destroy
  has_many :wishlists, through: :wishilist_items

  validates :name, presence: true
  validates :publisher, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :release_year, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1950 }
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :initialize_repository
  before_action :set_game, only: %i[ show edit update destroy ]

  def index
    @games = @game_repository.all
  end

  def show
  end

  def new
    @game = @game_repository.new
  end

  def edit
  end

  def create
    @game = @game_repository.new(game_params)

    respond_to do |format|
      if @game_repository.create(game_params)
        format.html { redirect_to @game, notice: "Game was successfully created." }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @game_repository.update(@game, game_params)
        format.html { redirect_to @game, notice: "Game was successfully updated." }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game_repository.destroy(@game)

    respond_to do |format|
      format.html { redirect_to admin_games_path, status: :see_other, notice: "Game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def initialize_repository
    @game_repository = GamesRepository.new
  end

  def set_game
    @game = @game_repository.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :publisher, :price, :release_year)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :initialize_repository
  before_action :set_game, only: %i[ show ]

  def index
    @games = @game_repository.all
  end

  def show
  end

  private

  def initialize_repository
    @game_repository = GamesRepository.new
  end

  def set_game
    @game = @game_repository.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :publisher, :price, :release_year)
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= game.publisher %>
  </p>

  <p>
    <strong>Platform:</strong>
    <%= game.platform %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= game.price %>
  </p>

  <p>
    <strong>Release year:</strong>
    <%= game.release_year %>
  </p>
</div>

app/views/games/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Games" %>

<h1>Games</h1>
<%= link_to "Usuários", users_path %> |
<%= link_to "Acessar Admin", admin_games_path %>

<div id="games">
  <% @games.each do |game| %>
    <%= render game %>
    <p>
      <%= link_to "Show this game", game %>
    </p>
  <% end %>
</div>

app/views/games/new.html.erb
<% content_for :title, "New game" %>

<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @game %>

<div>
  <%= link_to "Back to games", games_path %>
</div>