config/routes.rb
Rails.application.routes.draw do
  resources :games, only: [:index, :show]

  resources :users, except: [:destroy] do
    resources :wishlists, except: [:destroy] do
      resources :wishilist_items, only: [:create, :destroy]
    end
  end

  namespace :admin do
    resources :users
    resources :games
    resources :wishlists
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "games#index"
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  has_many :wishilist_items, dependent: :destroy
  has_many :games, through: :wishilist_items

  validates :nome, presence: true
  validates :user_id, presence: true
end

app/controllers/admin/wishlists_controller.rb
class Admin::WishlistsController < ApplicationController
  before_action :set_user
  before_action :set_wishlist, only: %i[show edit update]

  def index
    @wishlists = @user.wishlists
  end

  def show
  end

  def new
    @wishlist = @user.wishlists.build
  end

  def edit
  end

  def create
    @wishlist = @user.wishlists.build(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to user_wishlist_path(@user, @wishlist), notice: "Wishlist criada com sucesso." }
        format.json { render :show, status: :created, location: [@user, @wishlist] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to user_wishlist_path(@user, @wishlist), notice: "Wishlist criada com sucesso." }
        format.json { render :show, status: :ok, location: [@user, @wishlist] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_wishlist
    @wishlist = @user.wishlists.find(params.expect(:id))
  end

  def wishlist_params
    params.require(:wishlist).permit(:nome)
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_user
  before_action :set_wishlist, only: %i[show edit update destroy]

  def index
    @wishlists = @user.wishlists
  end

  def show
  end

  def new
    @wishlist = @user.wishlists.build
  end

  def edit
  end

  def create
    @wishlist = @user.wishlists.build(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to user_wishlist_path(@user, @wishlist), notice: "Wishlist criada com sucesso." }
        format.json { render :show, status: :created, location: [@user, @wishlist] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to user_wishlist_path(@user, @wishlist), notice: "Wishlist criada com sucesso." }
        format.json { render :show, status: :ok, location: [@user, @wishlist] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @wishlist.destroy!

    respond_to do |format|
      format.html { redirect_to user_wishlists_path(@user), status: :see_other, notice: "Wishlist deletada com sucesso." }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_wishlist
    @wishlist = @user.wishlists.find(params.expect(:id))
  end

  def wishlist_params
    params.require(:wishlist).permit(:nome)
  end
end

app/helpers/admin/wishlists_helper.rb
module Admin::WishlistsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/admin/wishlists/edit.html.erb
<h1>Editar Wishlist</h1>

<%= form_with model: [@user, @wishlist] do |f| %>
  <%= f.label :nome %>
  <%= f.text_field :nome %>

  <%= f.submit "Salvar" %>
<% end %>

<%= link_to "Voltar", user_wishlists_path(@user) %>

app/views/admin/wishlists/index.html.erb
<h1>Wishlists de <%= @user.name %></h1>

<%= link_to "Nova Wishlist", new_user_wishlist_path(@user) %>

<ul>
  <% @wishlists.each do |wishlist| %>
    <li>
      <%= link_to wishlist.nome, user_wishlist_path(@user, wishlist) %>
      |
      <%= link_to "Editar", edit_user_wishlist_path(@user, wishlist) %>
      |
      <%= link_to "Excluir", user_wishlist_path(@user, wishlist), method: :delete, data: { confirm: "Tem certeza?" } %>
    </li>
  <% end %>
</ul>

app/views/admin/wishlists/new.html.erb
<h1>Nova Wishlist</h1>

<%= form_with model: [@user, @wishlist] do |f| %>
  <%= f.label :nome %>
  <%= f.text_field :nome %>

  <%= f.submit "Criar" %>
<% end %>

<%= link_to "Voltar", user_wishlists_path(@user) %>

app/views/admin/wishlists/show.html.erb
<h1><%= @wishlist.nome %></h1>
<p>Dono: <%= @wishlist.user.name %></p>

<h2>Jogos nessa lista:</h2>
<ul>
  <% @wishlist.games.each do |game| %>
    <li>
      <%= game.name %>
      <%= link_to "Remover", user_wishlist_wishilist_item_path(@wishlist.user, @wishlist, game_id: game.id), method: :delete %>
    </li>
  <% end %>
</ul>

<h3>Adicionar novo jogo</h3>
<%= form_with url: user_wishlist_wishilist_items_path(@wishlist.user, @wishlist), method: :post do %>
  <%= select_tag :game_id, options_from_collection_for_select(Game.all, :id, :name) %>
  <%= submit_tag "Adicionar" %>
<% end %>

<%= link_to "Voltar", user_wishlists_path(@wishlist.user) %>